spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BLOODBANK
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create     # ✅ let Flyway handle schema, just validate on app startup

    show-sql: false
    properties:
      hibernate:
        default_schema: user_service
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  flyway:
    enabled: true
    baseline-on-migrate: true   # ✅ use this if your schema already exists (not empty DB)
    locations: classpath:db/migration
    validate-on-migrate: true   # ✅ to ensure consistency between schema and migrations

#  profiles:
#    active: prod
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
internal:
  donor:
    url: http://localhost:8082/donor/internal/api/donors
  service-token: my-shared-secret
kafka:
 bootstrap-servers: localhost:9092
consumer:
 group-id: bloodbank
 auto-offset-reset: earliest
 key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
 value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
producer:
 key-serializer: org.apache.kafka.common.serialization.StringSerializer
 value-serializer: org.apache.kafka.common.serialization.StringSerializer
 
eureka:
   instance:
     prefer-ip-address: true
logging:
   level:
    org.springframework.security: DEBUG
